require("dotenv").config();
const fs              = require("fs");
const express         = require("express");
const path            = require("path");
const yaml            = require("js-yaml");
const swaggerJSDoc    = require("swagger-jsdoc");
const swaggerUi       = require("swagger-ui-express");
const { createStore } = require("./stores");
const { runJokeAgent } = require("./agent/jokeAgent");
const { usageTracker } = require("./usage/usageTracker");
const { createProvider } = require("./providers");

const app  = express();
const PORT = process.env.PORT || 3000;

/* ── Initialise the joke store (local file or vector DB) ─────────────────── */
const store = createStore();
const provider = createProvider();

/* Hot-reload the local store on SIGHUP (kill -HUP <pid>) */
process.on("SIGHUP", () => {
  if (typeof store.reload === "function") {
    console.log("🔄  Reloading joke store...");
    store.reload();
  }
});

app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));

let ratings = [];

/* ── Swagger / OpenAPI ────────────────────────────────────────────────────
   openapi.yaml supplies the base spec (info, servers, tags, components).
   Per-endpoint `@swagger` JSDoc blocks below contribute the `paths` section.
   Mounted at /docs (interactive UI) and /openapi.json (raw spec).
─────────────────────────────────────────────────────────────────────────── */
const baseSpec = yaml.load(fs.readFileSync(path.join(__dirname, "openapi.yaml"), "utf8"));
delete baseSpec.paths; // paths live in @swagger JSDoc — keep one source of truth

const swaggerSpec = swaggerJSDoc({
  definition: baseSpec,
  apis: [__filename],
});

app.use(
  "/docs",
  swaggerUi.serve,
  swaggerUi.setup(swaggerSpec, {
    customSiteTitle: "Mood Joke Generator API",
    swaggerOptions:  { docExpansion: "list", defaultModelsExpandDepth: 0 },
  })
);
app.get("/openapi.json", (_req, res) => res.json(swaggerSpec));

/* ── Routes ──────────────────────────────────────────────────────────────── */

/**
 * @swagger
 * /get-joke:
 *   post:
 *     operationId: getJoke
 *     tags: [Jokes]
 *     summary: Get a joke matched to a mood
 *     description: |
 *       Accepts a free-text mood description and returns the most contextually
 *       appropriate joke from the datastore, selected by an AI agent.
 *
 *       The `mood` field accepts any natural language description — the agent
 *       invents a category label on the fly. Examples:
 *       - `"happy"` — agent picks a category like `happy`
 *       - `"feeling down after a rough day"` — agent picks something like `sad`
 *       - `"completely wiped out from jet lag"` — agent picks something like `tired`
 *       - `"my presentation just went sideways"` — agent picks something like `stressed`
 *
 *       The agent always calls the internal `pick_jokes` tool before selecting a
 *       joke, so candidates are drawn from the real datastore rather than
 *       generated by the LLM.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/GetJokeRequest'
 *           examples:
 *             simple_mood:
 *               summary: Exact category keyword
 *               value: { mood: happy }
 *             natural_language_tired:
 *               summary: Natural language — tired
 *               value: { mood: completely wiped out from jet lag }
 *             natural_language_stressed:
 *               summary: Natural language — stressed
 *               value: { mood: my presentation just went sideways and I want to hide }
 *             natural_language_sad:
 *               summary: Natural language — sad
 *               value: { mood: feeling really down after a rough week }
 *     responses:
 *       '200':
 *         description: A joke was successfully selected by the agent
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/GetJokeResponse'
 *             examples:
 *               success:
 *                 summary: Successful joke response
 *                 value:
 *                   joke: Why don't scientists trust atoms? Because they make up everything!
 *                   mood: happy
 *               natural_language:
 *                 summary: Natural language mood mapped by the agent
 *                 value:
 *                   joke: I stayed up all night to see where the sun went. Then it dawned on me.
 *                   mood: completely wiped out from jet lag
 *       '400':
 *         description: The `mood` field was missing, empty, or whitespace-only
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 *             examples:
 *               missing_mood:
 *                 summary: Missing mood field
 *                 value: { error: mood is required }
 *               empty_mood:
 *                 summary: Empty string
 *                 value: { error: mood is required }
 *       '500':
 *         description: The AI agent encountered an internal error
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 *             examples:
 *               agent_error:
 *                 summary: Agent failure
 *                 value: { error: The joke agent encountered an error. Please try again. }
 */
app.post("/get-joke", async (req, res) => {
  const mood = (req.body.mood || "").trim();

  if (!mood) {
    return res.status(400).json({ error: "mood is required" });
  }

  try {
    console.log(`😊  /get-joke mood="${mood}"`);
    const joke = await runJokeAgent(mood, store, provider);
    res.json({ joke, mood });
  } catch (err) {
    console.error("❌  Agent error:", err.message);
    res.status(500).json({ error: "The joke agent encountered an error. Please try again." });
  }
});

/**
 * @swagger
 * /rate-joke:
 *   post:
 *     operationId: rateJoke
 *     tags: [Ratings]
 *     summary: Submit a rating for a joke
 *     description: |
 *       Records a 1–3 star rating for a previously returned joke. The `mood` and
 *       `joke` fields are echoed back from the `/get-joke` response so each
 *       rating is linked to its context.
 *
 *       Ratings are stored in memory on the server and can be retrieved via
 *       `GET /stats`. The rating scale is:
 *       - `1` — Meh (😐)
 *       - `2` — Good (🙂)
 *       - `3` — Hilarious (😂)
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/RateJokeRequest'
 *           examples:
 *             hilarious:
 *               summary: Highest rating
 *               value:
 *                 mood: happy
 *                 joke: Why don't scientists trust atoms? Because they make up everything!
 *                 rating: 3
 *             meh:
 *               summary: Lowest rating
 *               value:
 *                 mood: tired
 *                 joke: I'm reading a book on anti-gravity. It's impossible to put down!
 *                 rating: 1
 *     responses:
 *       '200':
 *         description: Rating recorded successfully
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/RateJokeResponse'
 *             examples:
 *               success:
 *                 value: { message: Thanks for your feedback! }
 */
app.post("/rate-joke", (req, res) => {
  const { mood, joke, rating } = req.body;
  ratings.push({ mood, joke, rating: Number(rating), time: new Date() });
  console.log(`⭐  /rate-joke rating=${rating} mood="${mood}"`);
  res.json({ message: "Thanks for your feedback!" });
});

/**
 * @swagger
 * /usage:
 *   get:
 *     operationId: getUsage
 *     tags: [Usage]
 *     summary: Get Anthropic API usage and estimated cost
 *     description: |
 *       Returns cumulative Anthropic API usage for the current server process:
 *       token counters (input / output / cache create / cache read), estimated
 *       cost in USD based on configured per-MTok pricing, the latest rate-limit
 *       snapshot from Anthropic response headers, and session info.
 *
 *       ## Reset behaviour
 *       Counters are in-memory only and reset when the server restarts. For
 *       authoritative historical usage, query the Anthropic Admin API:
 *       `/v1/organizations/usage_report/messages`.
 *
 *       ## "Balance credit" note
 *       Anthropic does not expose a remaining-credit-balance endpoint via the
 *       public API. The `rateLimits` section is the closest equivalent — it
 *       reflects the request/token windows returned with the most recent
 *       response (including reset timestamps).
 *
 *       ## Pricing
 *       Defaults to `claude-sonnet-4-6` list pricing as of 2026. Override via
 *       env vars: `PRICE_INPUT_PER_MTOK`, `PRICE_OUTPUT_PER_MTOK`,
 *       `PRICE_CACHE_WRITE_PER_MTOK`, `PRICE_CACHE_READ_PER_MTOK`.
 *     responses:
 *       '200':
 *         description: Usage snapshot
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/UsageResponse'
 *             examples:
 *               with_usage:
 *                 summary: After several joke requests
 *                 value:
 *                   totals:
 *                     requests: 6
 *                     input_tokens: 4820
 *                     output_tokens: 612
 *                     cache_creation_input_tokens: 0
 *                     cache_read_input_tokens: 0
 *                     total_tokens: 5432
 *                     estimated_cost_usd: 0.023640
 *                   byModel:
 *                     claude-sonnet-4-6:
 *                       requests: 6
 *                       input_tokens: 4820
 *                       output_tokens: 612
 *                       cache_creation_input_tokens: 0
 *                       cache_read_input_tokens: 0
 *                       total_tokens: 5432
 *                       estimated_cost_usd: 0.023640
 *                   pricing_per_mtok_usd:
 *                     input: 3.00
 *                     output: 15.00
 *                     cache_write: 3.75
 *                     cache_read: 0.30
 *                   rateLimits:
 *                     lastUpdatedAt: "2026-05-26T14:30:00.000Z"
 *                     requests:      { limit: 50,    remaining: 44,    resetAt: "2026-05-26T14:31:00Z" }
 *                     tokens:        { limit: 50000, remaining: 44568, resetAt: "2026-05-26T14:31:00Z" }
 *                     input_tokens:  { limit: 40000, remaining: 35180, resetAt: "2026-05-26T14:31:00Z" }
 *                     output_tokens: { limit: 10000, remaining: 9388,  resetAt: "2026-05-26T14:31:00Z" }
 *                   session:
 *                     startedAt: "2026-05-26T14:00:00.000Z"
 *                     uptimeSeconds: 1800
 *                   notes:
 *                     - Token counts and costs are tracked per-process and reset on server restart.
 *                     - Costs are estimates calculated from the configured per-MTok pricing.
 *                     - Anthropic does not expose a remaining-credit-balance endpoint via the public API.
 *                     - For authoritative historical usage, query the Anthropic Admin API.
 *               fresh_server:
 *                 summary: Server just started — no requests yet
 *                 value:
 *                   totals:
 *                     requests: 0
 *                     input_tokens: 0
 *                     output_tokens: 0
 *                     cache_creation_input_tokens: 0
 *                     cache_read_input_tokens: 0
 *                     total_tokens: 0
 *                     estimated_cost_usd: 0
 *                   byModel: {}
 *                   pricing_per_mtok_usd:
 *                     input: 3.00
 *                     output: 15.00
 *                     cache_write: 3.75
 *                     cache_read: 0.30
 *                   rateLimits: null
 *                   session:
 *                     startedAt: "2026-05-26T14:00:00.000Z"
 *                     uptimeSeconds: 5
 */
app.get("/usage", (req, res) => {
  res.json(usageTracker.getSummary());
});

/**
 * @swagger
 * /stats:
 *   get:
 *     operationId: getStats
 *     tags: [Stats]
 *     summary: Get aggregate rating statistics
 *     description: |
 *       Returns the total number of ratings submitted, the average rating score
 *       across all jokes, and the full log of individual rating entries.
 *
 *       `averageRating` is returned as a string formatted to 2 decimal places
 *       (e.g. `"2.33"`), or `null` when no ratings have been submitted yet.
 *
 *       Note: ratings are stored in server memory and reset on server restart.
 *     responses:
 *       '200':
 *         description: Aggregate statistics and full rating log
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/StatsResponse'
 *             examples:
 *               with_ratings:
 *                 summary: Stats with existing ratings
 *                 value:
 *                   totalRatings: 3
 *                   averageRating: "2.33"
 *                   ratings:
 *                     - { mood: happy, joke: "Why don't scientists trust atoms? Because they make up everything!", rating: 3, time: "2025-06-01T10:00:00.000Z" }
 *                     - { mood: tired, joke: "I'm reading a book on anti-gravity. It's impossible to put down!",  rating: 2, time: "2025-06-01T10:05:00.000Z" }
 *                     - { mood: sad,   joke: "Why don't skeletons fight each other? They don't have the guts.",   rating: 2, time: "2025-06-01T10:10:00.000Z" }
 *               no_ratings:
 *                 summary: No ratings submitted yet
 *                 value:
 *                   totalRatings: 0
 *                   averageRating: null
 *                   ratings: []
 */
app.get("/stats", (req, res) => {
  const avg = ratings.length
    ? (ratings.reduce((s, r) => s + r.rating, 0) / ratings.length).toFixed(2)
    : null;
  res.json({ totalRatings: ratings.length, averageRating: avg, ratings });
});

app.listen(PORT, () => {
  const storeType = (process.env.STORE || "local").toUpperCase();
  console.log(`✅  Mood Joke Generator running → http://localhost:${PORT}`);
  console.log(`📦  Store: ${storeType}`);
  console.log(`📘  API Docs:    http://localhost:${PORT}/docs`);
});
